name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  envied: ^0.5.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml


flutter:

  assets:
    - assets/colors/
    - assets/lottie/
    - assets/icons/
    - assets/images/
