name: architecture_template
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Core Dependencies
  equatable: ^2.0.5

  #Network Dependencies
  vexana: ^3.5.4
  
  # State Management
  flutter_riverpod: ^2.4.9

  #Config
  easy_localization: ^3.0.3

  #Util
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0

  #Navigation
  auto_route: ^7.8.4

  widgets: 
    path: module/widgets

  gen:
    path: module/gen



dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  



flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/

  
